version: 0.2
phases:    
  install:
#    commands:
    runtime-versions:
      dotnet: latest
      
  build:
    commands:
      - cd src
      - dotnet build 
artifacts:
  files:
#    - '**/*'
     - appspec.yml
