version: 0.2
phases:    
  install:
    commands:
      - sudo apt update
      - sudo apt install snapd snapd-xdg-open -y
#      - systemctl start snapd.service
 #     - sudo snap install --classic code 
      - sudo apt install software-properties-common apt-transport-https wget
      - wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
      - sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      - sudo apt install code -y 
      - sudo apt update
#      - sudo apt upgrade -y
    runtime-versions:
      dotnet: latest
      
  build:
    commands:
      - cd src
      - dotnet build 
artifacts:
  files:
#    - '**/*'
     - appspec.yml
